/* =========================================================
   INVENZA V26 - Smart Inventory Intelligence
   Additive module. Reads/writes its own V26 metadata and keeps
   the existing V25 data model intact.
   ========================================================= */
(() => {
  'use strict';
  const K={items:'invenza_items_v2',meta:'invenza_asset_meta_v26',maintenance:'invenza_maintenance_v26',audit:'invenza_audit_v26',checks:'invenza_checks_v26',snapshots:'invenza_snapshots_v26',docs:'invenza_docs_v26',prefs:'invenza_prefs_v26'};
  const $=id=>document.getElementById(id), qa=(s,r=document)=>[...r.querySelectorAll(s)];
  const get=(k,f)=>{try{const x=localStorage.getItem(k);return x?JSON.parse(x):f}catch{return f}};
  const put=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
  const esc=s=>String(s??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));
  const rup=v=>'Rp '+new Intl.NumberFormat('id-ID').format(Number(v)||0);
  const items=()=>{const x=get(K.items,[]);return Array.isArray(x)?x:[]};
  const meta=()=>get(K.meta,{});
  const setMeta=(id,patch)=>{const m=meta();m[id]={...(m[id]||{}),...patch,updatedAt:new Date().toISOString()};put(K.meta,m);log('Asset diperbarui',id);};
  const toast=(title,msg)=>{const old=$('v26Toast');if(old)old.remove();const el=document.createElement('div');el.id='v26Toast';el.className='v26-toast';el.innerHTML=`<strong>${esc(title)}</strong><span>${esc(msg)}</span>`;document.body.appendChild(el);setTimeout(()=>el.remove(),3600)};
  const log=(action,ref='')=>{const a=get(K.audit,[]);a.unshift({id:'AUD-'+Date.now().toString(36).toUpperCase(),action,ref,time:new Date().toISOString()});put(K.audit,a.slice(0,250));};
  const navigate=id=>{const b=document.querySelector(`[data-section="${id}"], [data-section-target="${id}"]`);if(b)b.click()};
  const date=d=>d?new Intl.DateTimeFormat('id-ID',{dateStyle:'medium'}).format(new Date(d)):'-';
  const ageYears=d=>{if(!d)return 0;return Math.max(0,(Date.now()-new Date(d).getTime())/31557600000)};
  const health=i=>{let s=100;if(i.kondisi==='Rusak Ringan')s-=25;if(i.kondisi==='Rusak Berat')s-=60;if(Number(i.stok)<=0)s-=20;else if(Number(i.stok)<=3)s-=10;const fields=[i.kode,i.nama,i.kategori,i.ruangan,i.lokasi,i.supplier,i.penanggungJawab,i.tanggalPembelian];s-=fields.filter(x=>!String(x||'').trim()).length*4;if(ageYears(i.tanggalPembelian)>5)s-=10;return Math.max(0,Math.min(100,Math.round(s)))};
  const healthLabel=s=>s>=85?'Sangat Baik':s>=70?'Baik':s>=50?'Perlu Perhatian':'Kritis';
  const overall=()=>{const a=items();return a.length?Math.round(a.reduce((n,i)=>n+health(i),0)/a.length):100};
  const totalStock=()=>items().reduce((n,i)=>n+(Number(i.stok)||0),0);
  const totalAsset=()=>items().reduce((n,i)=>n+(Number(i.harga)||0)*(Number(i.stok)||0),0);
  const attention=()=>items().filter(i=>health(i)<70||i.kondisi!=='Baik'||Number(i.stok)<=3);
  const rooms=()=>{const map={};items().forEach(i=>{const r=i.ruangan||'Tanpa Ruangan';(map[r]??=[]).push(i)});return map};
  function ensureStyle(){if(!$('v26Style')){const l=document.createElement('link');l.id='v26Style';l.rel='stylesheet';l.href='./v26.css';document.head.appendChild(l)}}
  function makeUI(){
    if($('v26Dock'))return;
    const dock=document.createElement('div');dock.id='v26Dock';dock.innerHTML=`<div class="v26-dock-menu">
      <button class="v26-dock-btn" data-v26="intelligence"><b>◈ Intelligence</b><span>Health, insight, briefing</span></button>
      <button class="v26-dock-btn" data-v26="check"><b>✓ Check Mode</b><span>Pengecekan fisik & rekonsiliasi</span></button>
      <button class="v26-dock-btn" data-v26="asset"><b>▣ Asset Passport</b><span>Detail 360° dan label</span></button>
      <button class="v26-dock-btn" data-v26="location"><b>⌗ Location & Rack</b><span>Heatmap ruangan dan rak</span></button>
      <button class="v26-dock-btn" data-v26="maintenance"><b>⚙ Maintenance</b><span>Garansi dan pemeliharaan</span></button>
      <button class="v26-dock-btn" data-v26="snapshot"><b>◫ Snapshot</b><span>Versi data dan restore</span></button>
      <button class="v26-dock-btn" data-v26="more"><b>✦ More Tools</b><span>Demo, command, presentation</span></button>
    </div><button class="v26-dock-main" aria-label="Buka INVENZA V26">V26</button>`;
    document.body.appendChild(dock);
    dock.querySelector('.v26-dock-main').onclick=()=>dock.classList.toggle('open');
    dock.addEventListener('click',e=>{const b=e.target.closest('[data-v26]');if(!b)return;dock.classList.remove('open');({intelligence:showIntelligence,check:showCheck,asset:()=>showAssetPicker(),location:showLocation,maintenance:showMaintenance,snapshot:showSnapshots,more:showMore}[b.dataset.v26])?.()});
  }
  function overlay(id,title,kicker,body,wide=false){
    const old=$(id);if(old)old.remove();const root=document.createElement('div');root.id=id;root.className='v26-overlay';root.innerHTML=`<div class="v26-overlay-box ${wide?'wide':''}"><div class="v26-head"><div><span class="v26-kicker">${esc(kicker)}</span><h2>${esc(title)}</h2><p>INVENZA V26 Intelligence Layer</p></div><button class="v26-close" data-v26-close>ESC ×</button></div>${body}</div></div>`;document.body.appendChild(root);root.addEventListener('click',e=>{if(e.target===root||e.target.closest('[data-v26-close]'))root.remove()});return root;
  }
  function showIntelligence(){
    const a=items(), score=overall(), bad=attention().length, cats=new Set(a.map(i=>i.kategori).filter(Boolean)).size, rs=rooms();
    const stale=a.filter(i=>ageYears(i.tanggalPembelian)>=3).length;
    const insights=[];
    if(bad)insights.push(`Ada ${bad} barang yang perlu perhatian berdasarkan stok, kondisi, atau skor data.`); else insights.push('Tidak ada barang yang masuk daftar perhatian utama.');
    if(stale)insights.push(`${stale} barang berusia sekitar 3 tahun atau lebih dan layak ditinjau kembali.`);
    const missing=a.filter(i=>![i.kode,i.ruangan,i.lokasi,i.supplier].every(Boolean)).length;
    if(missing)insights.push(`${missing} entri belum lengkap pada kode, lokasi, ruangan, atau supplier.`);
    if(!insights.length)insights.push('Data inventaris terlihat stabil.');
    const r=overlay('v26Intelligence','Inventory Intelligence','V26 SMART INSIGHT',`<div class="v26-grid">
      <div class="v26-card"><span class="v26-label">INVENTORY HEALTH</span><div class="v26-health-ring" style="--score:${score}"><div><strong>${score}</strong><small>${healthLabel(score)}</small></div></div></div>
      <div class="v26-card"><span class="v26-label">TOTAL UNIT</span><div class="v26-number">${totalStock().toLocaleString('id-ID')}</div><span class="v26-label">${a.length} jenis barang</span></div>
      <div class="v26-card"><span class="v26-label">ASSET VALUE</span><div class="v26-number" style="font-size:21px">${rup(totalAsset())}</div><span class="v26-label">nilai stok terhitung</span></div>
      <div class="v26-card"><span class="v26-label">ATTENTION</span><div class="v26-number ${bad?'v26-warn':'v26-good'}">${bad}</div><span class="v26-label">perlu ditinjau</span></div>
    </div><div class="v26-grid two" style="margin-top:12px"><section class="v26-card"><h3>Daily Briefing</h3>${insights.map(x=>`<p>• ${esc(x)}</p>`).join('')}<div class="v26-actions"><button class="v26-action primary" data-v26-health-report>Buat Ringkasan</button><button class="v26-action" data-v26-presentation>Presentation Mode</button></div></section><section class="v26-card"><h3>Data Quality</h3><p>Kategori: <b>${cats}</b></p><p>Ruangan: <b>${Object.keys(rs).length}</b></p><p>Entri belum lengkap: <b>${missing}</b></p><div class="v26-progress"><span style="width:${Math.max(0,100-Math.round(missing/Math.max(1,a.length)*100))}%"></span></div></section></div>`,'');
    r.addEventListener('click',e=>{if(e.target.closest('[data-v26-presentation]'))showPresentation();if(e.target.closest('[data-v26-health-report]'))printIntelligence()});
  }
  function printIntelligence(){const a=items(),score=overall(),win=window.open('','_blank','width=900,height=700');if(!win){toast('Popup diblokir','Izinkan popup untuk membuat laporan.');return}win.document.write(`<html><head><title>INVENZA Intelligence Report</title><style>body{font-family:Arial;padding:35px;color:#102333}h1{margin-bottom:5px}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.box{border:1px solid #ccd;padding:15px;border-radius:12px}.big{font-size:28px;font-weight:800}table{width:100%;border-collapse:collapse;margin-top:20px}th,td{padding:8px;border-bottom:1px solid #ddd;text-align:left}</style></head><body><h1>INVENZA Inventory Intelligence</h1><p>${new Date().toLocaleString('id-ID')}</p><div class="grid"><div class="box"><small>HEALTH</small><div class="big">${score}%</div></div><div class="box"><small>JENIS</small><div class="big">${a.length}</div></div><div class="box"><small>UNIT</small><div class="big">${totalStock()}</div></div><div class="box"><small>NILAI</small><div class="big">${rup(totalAsset())}</div></div></div><table><tr><th>Barang</th><th>Kondisi</th><th>Stok</th><th>Health</th></tr>${a.map(i=>`<tr><td>${esc(i.nama)}</td><td>${esc(i.kondisi)}</td><td>${i.stok}</td><td>${health(i)}%</td></tr>`).join('')}</table><script>setTimeout(()=>print(),300)</script></body></html>`);win.document.close();log('Laporan intelligence dibuat')}
  function showAssetPicker(){
    const a=items();const r=overlay('v26AssetPicker','Asset Passport','INVENTORY 360°',`<p style="color:var(--v26-muted)">Pilih barang untuk membuka paspor digital lengkap.</p><div class="v26-table-wrap"><table class="v26-table"><thead><tr><th>Barang</th><th>Kode</th><th>Lokasi</th><th>Health</th><th>Aksi</th></tr></thead><tbody>${a.map(i=>`<tr><td><b>${esc(i.nama)}</b></td><td>${esc(i.kode)}</td><td>${esc(i.ruangan||'-')} / ${esc(i.lokasi||'-')}</td><td><span class="v26-pill ${health(i)>=70?'v26-good':'v26-warn'}"><i class="v26-dot"></i>${health(i)}%</span></td><td><button class="v26-action" data-v26-asset-id="${esc(i.id)}">Buka</button></td></tr>`).join('')}</tbody></table></div>`,'wide');
    r.addEventListener('click',e=>{const b=e.target.closest('[data-v26-asset-id]');if(b)showAsset(b.dataset.v26AssetId)});
  }
  function showAsset(id){
    const i=items().find(x=>x.id===id);if(!i)return;const m=meta()[id]||{};const logs=get(K.maintenance,[]).filter(x=>x.itemId===id).sort((a,b)=>b.time.localeCompare(a.time));
    const age=ageYears(i.tanggalPembelian), dep=Math.max(0,Number(i.harga||0)*(1-Math.min(.85,age/8))), warranty=m.warrantyEnd?new Date(m.warrantyEnd)>=new Date():false;
    const r=overlay('v26Asset','Asset Passport',esc(i.kode||i.id),`<div class="v26-grid two"><section class="v26-card"><div class="v26-health-ring" style="--score:${health(i)}"><div><strong>${health(i)}</strong><small>${healthLabel(health(i))}</small></div></div><h3 style="text-align:center;margin-top:14px">${esc(i.nama)}</h3><p style="text-align:center">${esc(i.kategori)} • ${esc(i.kondisi)}</p></section><section class="v26-card"><h3>Nilai & Usia</h3><p>Harga/unit: <b>${rup(i.harga)}</b></p><p>Stok: <b>${i.stok} ${esc(i.satuan)}</b></p><p>Estimasi nilai berjalan: <b>${rup(dep)}</b></p><p>Usia aset: <b>${age.toFixed(1)} tahun</b></p><p>Garansi: <b class="${warranty?'v26-good':'v26-warn'}">${m.warrantyEnd?date(m.warrantyEnd)+(warranty?' • Aktif':' • Berakhir'):'Belum diatur'}</b></p></section></div><div class="v26-grid two" style="margin-top:12px"><section class="v26-card"><h3>Identitas lokasi</h3><p>Ruangan: <b>${esc(i.ruangan||'-')}</b></p><p>Lokasi/rak: <b>${esc(i.lokasi||'-')}</b></p><p>Penanggung jawab: <b>${esc(i.penanggungJawab||'-')}</b></p><p>Supplier: <b>${esc(i.supplier||'-')}</b></p><div class="v26-actions"><button class="v26-action primary" data-edit-meta>Edit Metadata</button><button class="v26-action" data-print-label>Cetak Label</button></div></section><section class="v26-card"><h3>Timeline</h3><div class="v26-timeline">${logs.length?logs.slice(0,7).map(x=>`<div class="v26-event"><span class="v26-event-dot"></span><div><strong>${esc(x.type)}</strong><small>${date(x.time)} • ${esc(x.note||'')}</small></div></div>`).join(''):`<p>Belum ada riwayat maintenance.</p>`}</div></section></div><section class="v26-card" style="margin-top:12px"><h3>Metadata V26</h3><form class="v26-form" id="v26MetaForm"><div class="v26-grid two"><label>Garansi berakhir<input name="warrantyEnd" type="date" value="${esc(m.warrantyEnd||'')}"></label><label>Rak / slot<input name="rack" value="${esc(m.rack||i.lokasi||'')}"></label></div><label>Catatan tambahan<textarea name="note" rows="3">${esc(m.note||'')}</textarea></label><button class="v26-action primary" type="submit">Simpan Metadata</button></form></section>`,'wide');
    r.querySelector('[data-edit-meta]')?.addEventListener('click',()=>r.querySelector('#v26MetaForm')?.scrollIntoView({behavior:'smooth'}));
    r.querySelector('#v26MetaForm').addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.target);setMeta(id,{warrantyEnd:fd.get('warrantyEnd'),rack:fd.get('rack'),note:fd.get('note')});toast('Metadata tersimpan','Asset passport diperbarui.');r.remove();showAsset(id)});
    r.querySelector('[data-print-label]').addEventListener('click',()=>printLabel(i));
  }
  function printLabel(i){const payload=`INVENZA|${i.id}|${i.kode}|${i.nama}`;const qr='https://api.qrserver.com/v1/create-qr-code/?size=180x180&data='+encodeURIComponent(payload);const w=window.open('','_blank','width=450,height=600');if(!w){toast('Popup diblokir','Izinkan popup untuk mencetak label.');return}w.document.write(`<html><head><title>Label ${esc(i.kode)}</title><style>body{font-family:Arial;text-align:center;padding:30px} .label{width:280px;margin:auto;border:2px solid #102333;border-radius:18px;padding:20px}img{width:150px;height:150px}h2{margin:8px 0}p{margin:5px;color:#456}</style></head><body><div class="label"><strong>INVENZA</strong><h2>${esc(i.nama)}</h2><p>${esc(i.kode)}</p><p>${esc(i.ruangan||'-')} • ${esc(i.lokasi||'-')}</p><img src="${qr}" alt="QR"></div><script>setTimeout(()=>print(),1000)</script></body></html>`);w.document.close();log('Label dicetak',i.id)}
  function showCheck(){
    const a=items(), records=get(K.checks,{}), found=Object.keys(records).filter(id=>records[id].status==='found').length;
    const r=overlay('v26Check','Inventory Check Mode','FIELD AUDIT',`<div class="v26-grid"><div class="v26-card"><span class="v26-label">TERDAFTAR</span><div class="v26-number">${a.length}</div></div><div class="v26-card"><span class="v26-label">DITEMUKAN</span><div class="v26-number v26-good">${found}</div></div><div class="v26-card"><span class="v26-label">BELUM CEK</span><div class="v26-number v26-warn">${Math.max(0,a.length-found)}</div></div><div class="v26-card"><span class="v26-label">CHECK SESSION</span><div class="v26-number" style="font-size:16px">${date(new Date())}</div></div></div><div class="v26-actions"><button class="v26-action primary" data-v26-scan>Scan Barcode</button><button class="v26-action" data-v26-all-found>Tandai semua ditemukan</button><button class="v26-action" data-v26-reconcile>Rekonsiliasi</button></div><div class="v26-table-wrap"><table class="v26-table"><thead><tr><th>Barang</th><th>Lokasi sistem</th><th>Status lapangan</th><th>Aksi</th></tr></thead><tbody>${a.map(i=>{const s=records[i.id]?.status||'pending';return `<tr><td><b>${esc(i.nama)}</b><br><small>${esc(i.kode)}</small></td><td>${esc(i.ruangan||'-')} / ${esc(i.lokasi||'-')}</td><td><span class="v26-pill ${s==='found'?'v26-good':'v26-warn'}">${s==='found'?'✓ Ditemukan':'○ Belum cek'}</span></td><td><button class="v26-action" data-check-id="${esc(i.id)}">${s==='found'?'Batalkan':'Ditemukan'}</button></td></tr>`}).join('')}</tbody></table></div>`,'wide');
    r.addEventListener('click',e=>{const b=e.target.closest('[data-check-id]');if(b){const x=get(K.checks,{});x[b.dataset.checkId]={status:x[b.dataset.checkId]?.status==='found'?'pending':'found',time:new Date().toISOString()};put(K.checks,x);log('Check barang',b.dataset.checkId);r.remove();showCheck()}if(e.target.closest('[data-v26-all-found]')){const x=get(K.checks,{});a.forEach(i=>x[i.id]={status:'found',time:new Date().toISOString()});put(K.checks,x);log('Semua barang ditandai ditemukan');toast('Check selesai','Semua data ditandai ditemukan.');r.remove();showCheck()}if(e.target.closest('[data-v26-reconcile]'))showReconcile();if(e.target.closest('[data-v26-scan]'))scanBarcode();});
  }
  async function scanBarcode(){if(!('BarcodeDetector'in window)){toast('Scanner tidak tersedia','Browser ini belum mendukung BarcodeDetector. Gunakan input kode/manual check.');return}try{const det=new BarcodeDetector({formats:['code_128','ean_13','ean_8','qr_code','upc_a','upc_e']});const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}}});const v=document.createElement('video');v.autoplay=true;v.playsInline=true;v.srcObject=stream;const o=overlay('v26Scanner','Barcode Scanner','CAMERA');o.querySelector('.v26-overlay-box').insertAdjacentHTML('beforeend',`<video id="v26Video" style="width:100%;max-height:55vh;border-radius:16px;background:#000" autoplay playsinline></video><p style="color:var(--v26-muted)">Arahkan kamera ke barcode/QR. Kamera hanya digunakan selama mode scanner.</p>`);const vv=$('v26Video');vv.srcObject=stream;const tick=async()=>{if(!document.body.contains(vv)){stream.getTracks().forEach(t=>t.stop());return}try{const codes=await det.detect(vv);if(codes.length){const value=codes[0].rawValue;stream.getTracks().forEach(t=>t.stop());o.remove();const i=items().find(x=>x.kode===value||x.id===value);if(i){const x=get(K.checks,{});x[i.id]={status:'found',time:new Date().toISOString(),source:'scanner'};put(K.checks,x);log('Scan barcode',i.id);toast('Barang ditemukan',i.nama);showCheck()}else toast('Kode tidak ditemukan',value)}}catch{}requestAnimationFrame(tick)};requestAnimationFrame(tick)}catch(err){toast('Kamera tidak dapat dibuka','Periksa izin kamera browser.')} }
  function showReconcile(){const a=items(),c=get(K.checks,{});const rows=a.filter(i=>c[i.id]?.status!=='found');const r=overlay('v26Recon','Rekonsiliasi Inventaris','SYSTEM VS FIELD',`<p style="color:var(--v26-muted)">${rows.length} barang belum tercatat ditemukan pada sesi check terakhir.</p><div class="v26-table-wrap"><table class="v26-table"><thead><tr><th>Barang</th><th>Kode</th><th>Lokasi</th><th>Status</th></tr></thead><tbody>${rows.map(i=>`<tr><td>${esc(i.nama)}</td><td>${esc(i.kode)}</td><td>${esc(i.ruangan||'-')} / ${esc(i.lokasi||'-')}</td><td><span class="v26-pill v26-bad"><i class="v26-dot"></i>Belum ditemukan</span></td></tr>`).join('')||'<tr><td colspan="4">Semua barang sudah ditemukan.</td></tr>'}</tbody></table></div><div class="v26-actions"><button class="v26-action primary" data-export-recon>Export Rekonsiliasi</button></div>`,'wide');r.querySelector('[data-export-recon]')?.addEventListener('click',()=>download('invenza-reconciliation.json',JSON.stringify({createdAt:new Date().toISOString(),missing:rows},null,2),'application/json'))}
  function showLocation(){const rs=rooms();const r=overlay('v26Location','Location Intelligence','ROOM & RACK VISUALIZER',`<div class="v26-room-grid">${Object.entries(rs).map(([name,list])=>{const s=Math.round(list.reduce((n,i)=>n+health(i),0)/list.length);return `<div class="v26-room" data-room="${esc(name)}"><strong>${esc(name)}</strong><small>${list.length} jenis • ${list.reduce((n,i)=>n+(Number(i.stok)||0),0)} unit</small><div class="v26-room-score">${s}%</div><small>${healthLabel(s)}</small></div>`}).join('')}</div><section class="v26-card" style="margin-top:12px"><h3>Rack Visualizer</h3><p>Klik ruangan untuk melihat slot/lokasi yang tercatat.</p><div id="v26Rack" class="v26-rack"></div></section>`,'wide');const rack=r.querySelector('#v26Rack');r.querySelectorAll('[data-room]').forEach(b=>b.addEventListener('click',()=>{const list=rs[b.dataset.room];const by={};list.forEach(i=>(by[i.lokasi||'Tanpa lokasi']??=[]).push(i));rack.innerHTML=Object.entries(by).map(([loc,x])=>`<div class="v26-slot ${x.some(i=>i.kondisi!=='Baik')?'bad':'good'}"><strong>${esc(loc)}</strong><small>${x.length} jenis</small><small>${esc(x.map(i=>i.nama).slice(0,2).join(', '))}</small></div>`).join('')}));
  }
  function showMaintenance(){const a=items(),logs=get(K.maintenance,[]),m=meta();const upcoming=a.filter(i=>m[i.id]?.warrantyEnd&&new Date(m[i.id].warrantyEnd)-Date.now()<45*86400000&&new Date(m[i.id].warrantyEnd)>=new Date());const r=overlay('v26Maintenance','Maintenance Center','WARRANTY & CARE',`<div class="v26-grid"><div class="v26-card"><span class="v26-label">RIWAYAT</span><div class="v26-number">${logs.length}</div><span class="v26-label">maintenance event</span></div><div class="v26-card"><span class="v26-label">GARANSI</span><div class="v26-number v26-warn">${upcoming.length}</div><span class="v26-label">berakhir dalam 45 hari</span></div><div class="v26-card"><span class="v26-label">PERLU CEK</span><div class="v26-number v26-bad">${attention().length}</div><span class="v26-label">health / kondisi / stok</span></div><div class="v26-card"><span class="v26-label">DATA</span><div class="v26-number">${a.length}</div><span class="v26-label">asset terdaftar</span></div></div><div class="v26-table-wrap"><table class="v26-table"><thead><tr><th>Barang</th><th>Garansi</th><th>Kondisi</th><th>Aksi</th></tr></thead><tbody>${a.map(i=>`<tr><td><b>${esc(i.nama)}</b><br><small>${esc(i.kode)}</small></td><td>${m[i.id]?.warrantyEnd?date(m[i.id].warrantyEnd):'Belum diatur'}</td><td>${esc(i.kondisi)}</td><td><button class="v26-action" data-maint-id="${esc(i.id)}">Catat</button></td></tr>`).join('')}</tbody></table></div>`,'wide');r.addEventListener('click',e=>{const b=e.target.closest('[data-maint-id]');if(b)showMaintenanceForm(b.dataset.maintId)});
  }
  function showMaintenanceForm(id){const i=items().find(x=>x.id===id);const r=overlay('v26MaintForm','Catat Maintenance','MAINTENANCE EVENT',`<form class="v26-form" id="maintForm"><label>Jenis kegiatan<select name="type"><option>Pemeriksaan</option><option>Perbaikan</option><option>Pembersihan</option><option>Penggantian</option></select></label><label>Catatan<textarea name="note" rows="4" placeholder="Contoh: pemeriksaan kabel dan kondisi fisik"></textarea></label><label>Biaya<input name="cost" type="number" min="0" value="0"></label><button class="v26-action primary" type="submit">Simpan Riwayat</button></form>`);r.querySelector('#maintForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target),a=get(K.maintenance,[]);a.unshift({id:'MNT-'+Date.now().toString(36).toUpperCase(),itemId:id,type:f.get('type'),note:f.get('note'),cost:Number(f.get('cost')||0),time:new Date().toISOString()});put(K.maintenance,a.slice(0,500));log('Maintenance dicatat',id);toast('Maintenance tersimpan',i?.nama||'Barang');r.remove();showMaintenance()})}
  function showSnapshots(){const a=get(K.snapshots,[]),score=overall();const r=overlay('v26Snapshots','Snapshot & Recovery','VERSIONED DATA',`<div class="v26-grid three"><div class="v26-card"><span class="v26-label">SNAPSHOT</span><div class="v26-number">${a.length}</div></div><div class="v26-card"><span class="v26-label">CURRENT HEALTH</span><div class="v26-number">${score}%</div></div><div class="v26-card"><span class="v26-label">STORAGE</span><div class="v26-number" style="font-size:17px">${storageEstimate()}</div></div></div><div class="v26-actions"><button class="v26-action primary" data-snap-create>Buat Snapshot</button><button class="v26-action" data-snap-export>Export Snapshot</button></div><div class="v26-table-wrap"><table class="v26-table"><thead><tr><th>Waktu</th><th>Barang</th><th>Health</th><th>Aksi</th></tr></thead><tbody>${a.map((s,n)=>`<tr><td>${date(s.time)}</td><td>${s.items.length}</td><td>${s.health}%</td><td><button class="v26-action" data-snap-restore="${n}">Lihat</button></td></tr>`).join('')||'<tr><td colspan="4">Belum ada snapshot.</td></tr>'}</tbody></table></div>`,'wide');r.addEventListener('click',e=>{if(e.target.closest('[data-snap-create]')){const x=get(K.snapshots,[]);x.unshift({time:new Date().toISOString(),health:score,items:items()});put(K.snapshots,x.slice(0,20));log('Snapshot dibuat');toast('Snapshot dibuat','Versi inventaris tersimpan.');r.remove();showSnapshots()}if(e.target.closest('[data-snap-export]'))download('invenza-snapshot.json',JSON.stringify({version:'V26',createdAt:new Date().toISOString(),items:items(),meta:meta()},null,2),'application/json');const b=e.target.closest('[data-snap-restore]');if(b){const s=a[Number(b.dataset.snapRestore)];showSnapshotDetail(s)}})}
  function showSnapshotDetail(s){overlay('v26SnapDetail','Snapshot Detail','RECOVERY POINT',`<div class="v26-grid three"><div class="v26-card"><span class="v26-label">DIBUAT</span><div class="v26-number" style="font-size:17px">${date(s.time)}</div></div><div class="v26-card"><span class="v26-label">ITEMS</span><div class="v26-number">${s.items.length}</div></div><div class="v26-card"><span class="v26-label">HEALTH</span><div class="v26-number">${s.health}%</div></div></div><p style="color:var(--v26-muted)">Snapshot hanya disimpan sebagai recovery point. Gunakan Export JSON untuk membawa salinannya ke perangkat lain.</p><div class="v26-actions"><button class="v26-action primary" data-snap-download>Download Snapshot</button></div>`).querySelector('[data-snap-download]').addEventListener('click',()=>download('invenza-recovery-point.json',JSON.stringify(s,null,2),'application/json'))}
  function storageEstimate(){let n=0;for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);n+=(localStorage.getItem(k)||'').length}return (n/1024).toFixed(1)+' KB'}
  function showMore(){const r=overlay('v26More','V26 Command Center','ADVANCED TOOLS',`<div class="v26-grid two"><section class="v26-card"><h3>Global Command</h3><p>Cari aksi V26 dengan keyboard.</p><button class="v26-action primary" data-v26-command>Open Command Center</button></section><section class="v26-card"><h3>Demo Data Generator</h3><p>Tambahkan data uji tanpa menghapus inventaris yang ada.</p><div class="v26-actions"><button class="v26-action" data-demo="25">+25</button><button class="v26-action" data-demo="100">+100</button><button class="v26-action" data-demo="500">+500</button></div></section><section class="v26-card"><h3>Presentation Mode</h3><p>Tampilan dashboard besar untuk presentasi proyek.</p><button class="v26-action primary" data-v26-presentation>Mulai Presentasi</button></section><section class="v26-card"><h3>Focus Mode</h3><p>Sembunyikan elemen yang tidak diperlukan saat bekerja.</p><button class="v26-action" data-v26-focus>Aktifkan Focus Mode</button></section></div>`);r.addEventListener('click',e=>{if(e.target.closest('[data-v26-command]')){r.remove();openCommand()}if(e.target.closest('[data-v26-presentation]')){r.remove();showPresentation()}if(e.target.closest('[data-v26-focus]')){document.body.classList.toggle('v26-focus-mode');toast('Focus Mode',document.body.classList.contains('v26-focus-mode')?'Aktif':'Dinonaktifkan')}const b=e.target.closest('[data-demo]');if(b){generateDemo(Number(b.dataset.demo));r.remove()}})}
  function generateDemo(n){const base=Date.now();const cats=['Elektronik','ATK','Furniture','Buku','Peralatan'];const newItems=Array.from({length:n},(_,x)=>({id:'V26-'+base+'-'+x,kode:'D26-'+String(x+1).padStart(4,'0'),nama:`Demo Asset ${x+1}`,kategori:cats[x%cats.length],harga:[50000,125000,350000,750000,1500000][x%5],stok:1+(x%18),satuan:x%3?'Pcs':'Unit',supplier:`Supplier Demo ${(x%7)+1}`,kondisi:x%17===0?'Rusak Ringan':'Baik',ruangan:`Ruang ${(x%6)+1}`,lokasi:`Rak ${String.fromCharCode(65+(x%5))}${(x%8)+1}`,tanggalPembelian:new Date(Date.now()-((x%60)+1)*86400000*20).toISOString().slice(0,10),penanggungJawab:'Operator Demo',catatan:'Data uji V26.',gambar:'',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}));const all=items();put(K.items,all.concat(newItems));log('Demo data dibuat',String(n));toast('Demo data selesai',`${n} data tambahan dibuat.`);document.dispatchEvent(new Event('v26:datachanged'))}
  function showPresentation(){const a=items(),s=overall(),bad=attention().length,w=document.createElement('div');w.className='v26-presentation';w.innerHTML=`<div class="v26-presentation-top"><div><span class="v26-kicker">INVENZA V26</span><h1 style="font-size:clamp(30px,5vw,62px);margin:7px 0">Inventory Intelligence</h1><p style="color:#91a8ba">Live snapshot • ${new Date().toLocaleString('id-ID')}</p></div><div class="v26-live">● LIVE</div></div><div class="v26-presentation-grid"><div class="v26-presentation-card"><span class="v26-label">INVENTORY HEALTH</span><div class="v26-number">${s}%</div></div><div class="v26-presentation-card"><span class="v26-label">JENIS BARANG</span><div class="v26-number">${a.length}</div></div><div class="v26-presentation-card"><span class="v26-label">TOTAL UNIT</span><div class="v26-number">${totalStock().toLocaleString('id-ID')}</div></div><div class="v26-presentation-card"><span class="v26-label">ATTENTION</span><div class="v26-number">${bad}</div></div></div><div style="margin-top:30px;display:flex;gap:10px;flex-wrap:wrap"><button class="v26-action primary" id="v26ExitPresentation">Keluar Presentasi</button><button class="v26-action" id="v26PresentationReport">Cetak Ringkasan</button></div>`;document.body.appendChild(w);w.querySelector('#v26ExitPresentation').onclick=()=>w.remove();w.querySelector('#v26PresentationReport').onclick=printIntelligence}
  function openCommand(){let root=$('v26Command');if(root){root.remove();return}const commands=[['Dashboard','Buka dashboard',()=>navigate('dashboardSection')],['Data Barang','Buka data barang',()=>navigate('inventorySection')],['Intelligence','Health dan insight',showIntelligence],['Check Mode','Pengecekan fisik',showCheck],['Asset Passport','Paspor digital',showAssetPicker],['Location','Heatmap dan rack',showLocation],['Maintenance','Garansi dan maintenance',showMaintenance],['Snapshot','Recovery point',showSnapshots],['Presentation','Mode presentasi',showPresentation],['Generate 25 Demo','Tambah 25 data uji',()=>generateDemo(25)],['Toggle Focus','Fokus kerja',()=>document.body.classList.toggle('v26-focus-mode')]];root=document.createElement('div');root.id='v26Command';root.className='v26-command';root.innerHTML=`<div class="v26-command-box"><input id="v26CommandInput" class="v26-command-input" placeholder="Cari perintah V26... (ESC untuk tutup)" autocomplete="off"><div class="v26-command-list"></div></div>`;document.body.appendChild(root);const render=()=>{const t=$('v26CommandInput').value.toLowerCase();root.querySelector('.v26-command-list').innerHTML=commands.filter(c=>(c[0]+' '+c[1]).toLowerCase().includes(t)).map((c,i)=>`<button class="v26-command-item" data-i="${i}"><strong>${esc(c[0])}</strong><span>${esc(c[1])}</span></button>`).join('')};render();$('v26CommandInput').oninput=render;root.addEventListener('click',e=>{const b=e.target.closest('[data-i]');if(b){commands[Number(b.dataset.i)][2]();root.remove()}if(e.target===root)root.remove()});$('v26CommandInput').focus()}
  function download(name,data,type='text/plain'){const blob=new Blob([data],{type}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
  function keyboard(){document.addEventListener('keydown',e=>{if(e.key==='Escape'){$('v26Command')?.remove();qa('.v26-overlay').forEach(x=>x.remove());$('v26Dock')?.classList.remove('open')}if((e.ctrlKey||e.metaKey)&&e.shiftKey&&e.key.toLowerCase()==='k'){e.preventDefault();openCommand()}if((e.ctrlKey||e.metaKey)&&e.shiftKey&&e.key.toLowerCase()==='p'){e.preventDefault();showPresentation()}if(e.key==='F2'){e.preventDefault();showIntelligence()}})}
  function registerSW(){if('serviceWorker'in navigator)navigator.serviceWorker.ready.then(()=>navigator.serviceWorker.register('./service-worker.js')).catch(()=>{})}
  function boot(){ensureStyle();makeUI();keyboard();registerSW();log('V26 aktif');window.addEventListener('online',()=>toast('Online','INVENZA kembali terhubung.'));window.addEventListener('offline',()=>toast('Offline','INVENZA tetap dapat digunakan secara lokal.'));document.addEventListener('v26:datachanged',()=>{});}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
